[package]
name = "flappy_bird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigma-3d = "0.2.14"
rand = "0.9.0"
image = { version = "0.25.5", features = ["png"] }